//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaPowert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int Alumno_ID { get; set; }
        public int Alumno_Control { get; set; }
        public string Alumno_Nombre { get; set; }
        public string Alumno_Apellido { get; set; }
        public int Alumno_Grupo { get; set; }
        public bool Alumno_Estado { get; set; }
        public int ID_Grupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
