//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaPowert
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscuelaEntities1 : DbContext
    {
        public EscuelaEntities1()
            : base("name=EscuelaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Ciclo> Ciclo { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Plan_Estudio> Plan_Estudio { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
