//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaPowert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public int Profesor_ID { get; set; }
        public string Profesor_Nombre { get; set; }
        public int ID_Grupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
