//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaPowert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo_Info
    {
        public int Info_ID { get; set; }
        public int ID_Grupo { get; set; }
        public int ID_Profesor { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
